### ISSUE TITLE
Incorrect private key?

### ISSUE THREAD

**Issue by giekaton** [Domraider/php-eth-raw-tx#13]
Maybe you can help. Everything works fine, except I get Incorrect private key error when trying to execute "send_ether.php"

Fatal error: Uncaught Exception: Incorrect private key in /var/www/html/php-eth-raw-tx/src/EthereumRawTx/Transaction.php:132 Stack trace: #0 /var/www/html/php-eth-raw-tx/src/EthereumRawTx/Transaction.php(96): EthereumRawTx\Transaction->sign(Object(BitWasp\Buffertools\Buffer)) #1 /var/www/html/php-eth-raw-tx/examples/send_ether.php(23): EthereumRawTx\Transaction->getRaw(Object(BitWasp\Buffertools\Buffer), Object(BitWasp\Buffertools\Buffer)) #2 {main} thrown in /var/www/html/php-eth-raw-tx/src/EthereumRawTx/Transaction.php on line 132

The private key part of "send_ether.php" looks like this:
```
$pk = \BitWasp\Buffertools\Buffer::hex(getenv("77ad7f185376b7ae24a28a16f0b4a615bab1a977ca1bb6099f400c9bb8b5e775"));
if (!$pk) {
    exit("/!\ Set private key in PHP_ETH_RAW_TX_PK env var" . PHP_EOL);
}
```

Any ideas?

**Edit:** It seems that the problem is with getenv.

If I pass private key without getenv, the TX is created but it cannot be broadcasted with the error "Invalid sender".

If I pass pk with getenv, then this returns bool(false) and this is why the problem mentioned above occurs.

**Edit2:** Looks like I have finally sorted this out. I was using Ropsten (ID: 3) network and trying to broadcast transaction (as in first Edit) on the main network. Now changed to the Ropsten and it seems to be working... still some errors, but getting closer

**Edit3:** Latest error is with transaction value. Somehow it adds gasprice to the beginning of value which is defined as "0":
The account you tried to send transaction from does not have enough funds. Required 1966080000000000000 and got: 998121760000000000."},"id":1}

**Edit4:** Removed two '00' from $this->gasPrice = null === $gasPrice ? Buffer::int('10000000000000') : $gasPrice; in Transaction.php on line 75 and now my transaction was successfully broadcasted to the network, but it is not picked up by the indexer for quite some time now: https://ropsten.etherscan.io/tx/0xfce5c029cc7f0ce9b140b5508c93a2892c681d04eacfa3e93e3c3cfa26819cbe - In comparison, broadcasted another transaction signed with MEW and it was picked up instantly.

**Edit5:** Finally, the transaction was picked up. I needed to increase the nonce only +1 relative to my previous transaction.
https://ropsten.etherscan.io/tx/0xc6bede756e9dcb9f4725657e12e3b8c11b1adf3b0f4caa5282dd1e9b3fee1b1d

**Comment by etienneroudeix** [comment]
Hi @dziungles, nice to see someone is using this  project :)
Do not hesitate if you face any difficulty.
Cheers.
