### ISSUE TITLE
Uncaught TypeError: in Transaction.php:203

### ISSUE THREAD

**Issue by vladi550821** [Domraider/php-eth-raw-tx#29]
After starting send_ether.php in Ropsten I got:
Fatal error:  Uncaught TypeError: Argument 2 passed to secp256k1_ecdsa_sign_recoverable() must be of the type resource or null, string given in ../domraider/php-eth-raw-tx/src/EthereumRawTx/Transaction.php:203
send_ether.php is with following code:
<?php
require_once __DIR__ . '/../vendor/autoload.php';

$nonce = \BitWasp\Buffertools\Buffer::int(3);
$to = \BitWasp\Buffertools\Buffer::hex('aFB477aE6eBc03C9a48cd96eC57a2456Aa986422');
$value = \BitWasp\Buffertools\Buffer::int('12345678901234563');
$data = null;

// $pk = \BitWasp\Buffertools\Buffer::hex(getenv("PHP_ETH_RAW_TX_PK"));
$pk = \BitWasp\Buffertools\Buffer::hex('472cc0b144acf430b4b2aa8023ff90cb2d11535f9215a61ec360a7e0b9e4454c');
if (!$pk) {
    exit("/!\ Set private key in PHP_ETH_RAW_TX_PK env var" . PHP_EOL);
}
$chainId = \BitWasp\Buffertools\Buffer::int(3); // ropsten
$tx = new \EthereumRawTx\Transaction(
    $to,
    $value,
    $data,
    $nonce
);

$raw = $tx->getRaw($pk, $chainId);

echo "Generated raw transaction :" . PHP_EOL;
echo $raw->getHex() . PHP_EOL;

[test_output.txt](https://github.com/Domraider/php-eth-raw-tx/files/3272825/test_output.txt)

**Comment by etienneroudeix** [comment]
Hi @vladi550821,
Did you correctly set secret key ?
If you let the example untouched, you can do it with :
```
export PHP_ETH_RAW_TX_PK=123123123123123123131231312312
```
(withtout 0x prefix).

Else you can do it incode :
```
$pk = \BitWasp\Buffertools\Buffer::hex('123123123123123123131231312312');
```

I just noticed I used the variable name `$pk` which is misleading and actually is the secret key and not the public key.

**Comment by vladi550821** [comment]
Thank you @etienneroudeix. I just solved the issue, but got new one.

Initially I installed secp256k1 and secp256k1-php-0.1.2 as suggested by you, but secp256k1-php failed to compile. The issue is described [here](https://github.com/Bit-Wasp/secp256k1-php/issues/124). 

I used commit 95e99f196fd08a8b2c236ab99d7e7fec8f6dc78f of bitcoin-core/secp256k1 and managed to compile secp256k1-php-0.1.2. 

Now **send_ether.php** produces raw transactions, and these transactions return hash when sent. But I got another issue - *some* transactions produce hash, which is visible on nodesmith, but are not broadcasted,  don't exist at etherscan.io and transactionCount  is not incremented. I use gasPrice = 2Gwei and gasLimit = 22000 and passed transactions have fees of 0.00042 or more - more then enough.
Do you have any ideas about the reason? Thank you!

My test code is:

` $wallet = 'test';
        $nodesmith = new \silverhead\nodesmithapi\NodesmithApi; /my API to nodesmuth

        $n = hexdec($nodesmith->transaction_count(config("env.$wallet")['public'])->result);
        $nonce = \BitWasp\Buffertools\Buffer::int($n);
        $gasPrice =  \BitWasp\Buffertools\Buffer::int('2000000000');
        $gasLimit = \BitWasp\Buffertools\Buffer::int('23000');                  
        $to = \BitWasp\Buffertools\Buffer::hex('aFB477aE6eBc03C9a48cd96eC57a2456Aa986422'); 
        $value = \BitWasp\Buffertools\Buffer::hex($nodesmith->ether2wei(0.1));
        $data = null;
        $p = substr(config("app.$wallet")['private'],2);
        $pk = \BitWasp\Buffertools\Buffer::hex($p);

        if (!$pk) {
            exit("/!\ Set private key in PHP_ETH_RAW_TX_PK env var" . PHP_EOL);
        }
        $chainId = \BitWasp\Buffertools\Buffer::int(3); // ropsten
        $tx = new \EthereumRawTx\Transaction(
            $to,
            $value,
            $data,
            $nonce,
            $gasPrice,
            $gasLimit
        );
        $raw = $tx->getRaw($pk, $chainId);
        echo $raw->getHex();`

**Comment by vladi550821** [comment]
Solved! All the issues are from Nodesmith. On Infura it works like a charm..

**Comment by etienneroudeix** [comment]
@vladi550821 Nice to hear this :)
