### ISSUE TITLE
Can't create transaction

### ISSUE THREAD

**Issue by khrigo** [Domraider/php-eth-raw-tx#35]
Uncaught TypeError: Argument 2 passed to secp256k1_ecdsa_sign_recoverable() must be of the type resource or null, string given 

\Transaction->getRaw() #3 {main} thrown in /var/www/html/eth/src/EthereumRawTx/Transaction.php on line 203

**Comment by etienneroudeix** [comment]
Hi, can you share some code to reproduce it please.

**Comment by khrigo** [comment]
> Hi, can you share some code to reproduce it please.

It's example **send_ether.php**

**Comment by khrigo** [comment]
And other examples. 

For example, **call_smart_contract.php** is working. But all examples with **Transaction.php** don’t work.

**Comment by dellasorte** [comment]
I have actually the same issue. I am not sure what is the problem but I suppose it's PHP version . I using 7.4 but according to some definitions in secp256k1-php it should work on PHP 7.0.2 I have same code as in eth_send example, just added $gasPrice and $gasLimit parameters.

**Comment by dellasorte** [comment]
Alright I solved that. All you need to do is
```
wget https://github.com/Bit-Wasp/secp256k1-php/archive/v0.1.2.zip
unzip v0.1.2.zip
cd secp256k1-php-0.1.2/secp256k1
sed -i 's/secp256k1_ecdh(ctx, resultChars, pubkey, privKey->val);/secp256k1_ecdh(ctx, resultChars, pubkey, privKey->val, NULL, NULL);/' secp256k1.c
make clean
phpize
./configure --with-secp256k1
make
sudo make install
```

**Comment by etienneroudeix** [comment]
Hi @dellasorte Thank you for investigating. Do not hesitate to update the README and make a PR, it would be appreciated.
